routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/ 
Route::get('/', 'HomeController@index')->name('index');
Route::get('/produk', 'ProductController@index')->name('product');
Route::get('/pages/{slug}', 'PagesController@show')->name('detail.pages');
Route::get('/produk-detail/{slug}', 'ProductController@show')->name('detail.product');
// Route::get('/tentang-kami', 'HomeController@about')->name('about');
// Route::get('/program-reseller', 'HomeController@reseller')->name('reseller');
Route::get('/testimonial', 'HomeController@testimonial')->name('testimonial');
Route::get('/kontak-kami', 'HomeController@contact')->name('contact');
Route::post('/message/save', 'MessageController@store')->name('message.store');
Route::get('/category/{categoryName}', 'ProductController@index')->name('category');

Route::post('/search', 'ProductSearchController@index')->name('search.product');

Route::get('/blog/all', 'BlogController@index')->name('all.blog');
Route::get('/blog/{blogSlug}', 'BlogController@show')->name('detail.blog');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login')->name('client.login.submit');

Route::prefix('ajax')->name('ajax.')->group(function(){
    Route::get('premium', 'AjaxController@getPremiumProduct')->name('premium');
    Route::get('sale', 'AjaxController@getSaleProduct')->name('sale');
    Route::get('new', 'AjaxController@getNewProduct')->name('new');
    Route::get('available', 'AjaxController@getAvailProduct')->name('available');
    Route::get('soon', 'AjaxController@getSoonProduct')->name('soon');

    Route::get('color/{color?}', 'AjaxController@getColorProduct')->name('color');
});

        //preview blog
    Route::get('/preview/{blogSlug}', 'BlogController@preview')->name('preview.blog')->middleware('admin');
    Route::get('/page-preview/{pagesSlug}', 'PagesController@preview')->name('pagepreview.blog')->middleware('admin');

Route::prefix('admin')->name('admin.')->namespace('Admin')->group(function(){
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('/login', 'Auth\LoginController@login')->name('login.submit');
    Route::post('logout', 'Auth\LoginController@logout')->name('logout');
    Route::get('register','Auth\LoginController@showRegisterPage');
    Route::post('register', 'Auth\LoginController@register')->name('register.submit');

    Route::group(['middleware' => ['admin']], function () {

        Route::get('kontak-kami', 'ContactUsController@index')->name('contact_us');
        Route::post('kontak-kami/save', 'ContactUsController@save')->name('contact_us.save');

        // profile
        Route::get('profile','HomeController@showProfile');


        // dashboard
        Route::get('dashboard', 'HomeController@dashboard')->name('dashboard');


        // product
        Route::get('products', 'ProductController@index')->name('products');
        Route::get('product/add', 'ProductController@create')->name('add.product');
        Route::post('product/save', 'ProductController@store')->name('create.product');
        Route::get('product/edit/{id}', 'ProductController@edit')->name('edit.product');
        Route::post('product/update', 'ProductController@update')->name('update.product');
        Route::get('product/remove/{id}', 'ProductController@destroy')->name('remove.product');
        Route::post('product/removeall', 'ProductController@destroyAll')->name('removeall.product');

        // contact master
        Route::get('contact_master', 'ContactController@index')->name('contact');
        Route::get('contact_master/add', 'ContactController@create')->name('add.contact');
        Route::post('contact_master/save', 'ContactController@store')->name('create.contact');
        Route::get('contact_master/edit/{id}', 'ContactController@edit')->name('edit.contact');
        Route::post('contact_master/update', 'ContactController@update')->name('update.contact');
        Route::get('contact_master/remove/{id}', 'ContactController@destroy')->name('remove.contact');
        Route::post('contact_master/removeall', 'ContactController@destroyAll')->name('removeall.contact');

        //category product
        Route::get('product/category', 'ProductCategoryController@index')->name('category.product');
        Route::get('category/add', 'ProductCategoryController@create')->name('create.category');
        Route::get('category/edit/{id}', 'ProductCategoryController@edit')->name('edit.category');
        Route::post('category/save', 'ProductCategoryController@store')->name('store.category');
        Route::post('category/update', 'ProductCategoryController@update')->name('update.category');
        Route::get('category/remove/{id}', 'ProductCategoryController@destroy')->name('remove.category');
        Route::post('category/removeall', 'ProductCategoryController@destroyAll')->name('removeall.category');


        //blogs
        Route::get('blogs', 'BlogController@index')->name('blogs');
        Route::get('blog/add', 'BlogController@create')->name('create.blog');
        Route::post('blog/save', 'BlogController@store')->name('store.blog');
        Route::get('blog/edit/{id}', 'BlogController@edit')->name('edit.blog');
        Route::post('blog/update', 'BlogController@update')->name('update.blog');
        Route::get('blog/remove/{id}', 'BlogController@destroy')->name('remove.blog');
        Route::post('blog/removeall', 'BlogController@destroyAll')->name('removeall.blog');


        //category blog
        Route::get('blog/category', 'BlogCategoryController@index')->name('category.blog');
        Route::get('blog/category/add', 'BlogCategoryController@create')->name('add.category.blog');
        Route::post('blog/category/save', 'BlogCategoryController@store')->name('create.category.blog');
        Route::get('blog/category/edit/{id}', 'BlogCategoryController@edit')->name('remove.category.blog');
        Route::post('blog/category/update', 'BlogCategoryController@update')->name('update.category.blog');
        Route::get('blog/category/remove/{id}', 'BlogCategoryController@destroy')->name('remove.category.blog');
        Route::post('blog/category/removeall', 'BlogCategoryController@destroyAll')->name('removeall.category.blog');


        //tags blog
        Route::get('blog/tag', 'BlogTagController@index')->name('tag.blog');
        Route::get('blog/tag/add', 'BlogTagController@create')->name('add.tag.blog');
        Route::post('blog/tag/save', 'BlogTagController@store')->name('create.tag.blog');
        Route::get('blog/tag/edit/{id}', 'BlogTagController@edit')->name('edit.tag.blog');
        Route::post('blog/tag/update', 'BlogTagController@update')->name('update.tag.blog');
        Route::get('blog/tag/remove/{id}', 'BlogTagController@destroy')->name('remove.tag.blog');
        Route::post('blog/tag/removeall', 'BlogTagController@destroyAll')->name('removeall.tag.blog');


        //menu setting
        Route::get('menu', 'MenuController@index')->name('menu');
        Route::get('menu/add', 'MenuController@create')->name('add.menu');
        Route::post('menu/save', 'MenuController@store')->name('create.menu');
        Route::get('menu/edit/{id}', 'MenuController@edit')->name('edit.menu');
        Route::post('menu/update', 'MenuController@update')->name('update.menu');
        Route::get('menu/remove/{id}', 'MenuController@destroy')->name('remove.menu');
        Route::post('menu/removeall', 'MenuController@destroyAll')->name('removeall.menu');

        //pages
        Route::get('pages', 'PagesController@index')->name('pages');
        Route::get('pages/add', 'PagesController@create')->name('add.pages');
        Route::post('pages/save', 'PagesController@store')->name('create.pages');
        Route::get('pages/edit/{id}', 'PagesController@edit')->name('edit.pages');
        Route::post('pages/update', 'PagesController@update')->name('update.pages');
        Route::get('pages/remove/{id}', 'PagesController@destroy')->name('remove.pages');
        Route::post('pages/removeall', 'PagesController@destroyAll')->name('removeall.pages');

        //testimonial
        Route::get('testimonial', 'TestimonialController@index')->name('show.testimonial');
        Route::get('testimonial/add', 'TestimonialController@create')->name('add.testimonial');
        Route::post('testimonial/save', 'TestimonialController@store')->name('create.testimonial');
        Route::get('testimonial/edit/{id}', 'TestimonialController@edit')->name('update.TestimonialController');
        Route::post('testimonial/update', 'TestimonialController@update')->name('update.TestimonialController');    
        Route::get('testimonial/remove/{id}', 'TestimonialController@destroy')->name('remove.TestimonialController');
        Route::post('testimonial/removeall', 'TestimonialController@destroyAll')->name('removeall.TestimonialControllerg');

        //general
        Route::get('general', 'GeneralController@index')->name('logo');
        Route::post('general/save_logo_header', 'GeneralController@save_logo_header')->name('save_header.logo');
        Route::post('general/save_logo_footer', 'GeneralController@save_logo_footer')->name('save_footer.logo');
        Route::post('general/save_banner', 'GeneralController@save_banner')->name('SaveBanner');
        Route::post('general/save_prod_banner', 'GeneralController@save_prod_banner')->name('SaveProdBanner');

        // users
        Route::get('admins', 'AdminsController@index')->name('admins');

resources/views/admin/about.blade.php
@extends('layouts.admin')
@section('content')

<div class="page-hero page-container" id="page-hero">
    <div class="padding d-flex">
        <div class="page-title">
            <h2 class="text-md text-highlight">Tentang Kami</h2><small class="text-muted">Format data into a table</small></div>
            <div class="flex"></div>
            <div><a href="{{ url('/admin/blog/add') }}" class="btn btn-md btn-primary"><span class="d-none d-sm-inline mx-1">Ubah Tentang Kami</span> <i data-feather="arrow-right"></i></a></div>
    </div>
</div>
<div class="page-content page-container" id="page-content">
    <div class="padding">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title">Tentang Kami</h5>
                    </div>
                    <div class="card-body">
                        <p class="card-text">{{ $about->description }}</p>
                        <object width="400" 
                        data="{{ $about->yt_video_url }}">
                        </object>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/blank.blade.php
@extends('layouts.admin')
@section('content')

@endsection

resources/views/admin/login.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Login | {{ config('app.name', 'Kaheci - Web Application') }}</title>
    <meta name="description" content="Responsive, Bootstrap, BS4">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">
    <link rel="stylesheet" href="{{ asset('admin/assets/css/site.min.css') }}">
</head>

<body class="layout-row">
    <div class="flex">
        <div class="w-xl w-auto-sm mx-auto py-5">
            <div class="p-4 d-flex flex-column h-100">
                <a href="{{ url('/') }}" class="navbar-brand align-self-center">
                    <img src="{{ asset('images/logo.png') }}" alt="">
                    <span class="hidden-folded d-inline l-s-n-1x align-self-center">Kaheci</span></a>
            </div>
            <div class="card">
                <div id="content-body">
                    <div class="p-3 p-md-5">
                        <h5>Welcome back</h5>
                        <p><small class="text-muted">Login to manage your account</small></p>
                        <form class="" role="form" method="POST" action="{{ route('admin.login.submit') }}">
                            @csrf
                            <div class="form-group">
                                <label>Email</label>
                                <!--input type="email" class="form-control" placeholder="Enter email"-->
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email" autofocus placeholder="Enter email">

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror

                            </div>
                            <div class="form-group">
                                <label>Password</label>
                                <!--input type="password" class="form-control" placeholder="Password"-->
                                <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="current-password" placeholder="Password">
                                <!--div class="my-3 text-right"><a href="forgot-password.html" class="text-muted">Forgot password?</a></div-->

                                @error('password')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                            <div class="checkbox mb-3">
                                <label class="ui-check">
                                    <input type="checkbox" name="remember" id="remember" {{ old('remember') ? 'checked' : '' }}><i></i> Remember me</label>
                            </div>
                            <button type="submit" class="btn btn-primary mb-4">Sign in</button>
                            <!--div>Do not have an account? <a href="signup.1.html" class="text-primary">Sign up</a></div-->
                        </form>
                    </div>
                </div>
            </div>
            <div class="text-center text-muted">2019 &copy; Copyright. Kaheci</div>
        </div>
    </div>
    <script src="{{ asset('admin/assets/js/site.min.js') }}"></script>
</body>

</html>

resources/views/admin/register.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Register | {{ config('app.name', 'Kaheci - Web Application') }}</title>
    <meta name="description" content="Responsive, Bootstrap, BS4">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">
    <link rel="stylesheet" href="{{ asset('admin/assets/css/site.min.css') }}">
</head>

<body class="layout-row">
    <div class="flex">
        <div class="w-xl w-auto-sm mx-auto py-5">
            <div class="p-4 d-flex flex-column h-100">
                <a href="{{ url('/') }}" class="navbar-brand align-self-center">
                    <img src="{{ asset('images/logo.png') }}" alt="">
                    <span class="hidden-folded d-inline l-s-n-1x align-self-center">Kaheci</span></a>
            </div>
            <div class="card">
                <div id="content-body">
                    <div class="p-3 p-md-5">
                        <h5>Admin {{ __('Register') }}</h5>
                        <p><small class="text-muted">Register to create your account</small></p>
                        <form class="" role="form" method="POST" action="{{ route('admin.register.submit') }}">
                            @csrf
                            <div class="form-group">
                                <label>Name</label>
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus placeholder="Enter admin name">

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror

                            </div>

                            <div class="form-group">
                                <label>No. Telp</label>
                                <input id="no_telp" type="number" class="form-control @error('no_telp') is-invalid @enderror" name="no_telp" value="{{ old('no_telp') }}" required autocomplete="no_telp" autofocus placeholder="Enter admin telp">

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror

                            </div>

                            <div class="form-group">
                                <label>Email</label>
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email" placeholder="Enter email">

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror

                            </div>
                            <div class="form-group">
                                <label>Password</label>
                                <!--input type="password" class="form-control" placeholder="Password"-->
                                <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="current-password" placeholder="Password">

                                @error('password')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label>{{ __('Confirm Password') }}</label>
                                <input id="password_confirmation" type="password" class="form-control @error('password_confirmation') is-invalid @enderror" name="password_confirmation" required placeholder="Confirm Password">

                                @error('password_confirmation')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>

                            <button type="submit" class="btn btn-primary mb-4">{{ __('Register') }}</button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="text-center text-muted">2019 &copy; Copyright. Kaheci</div>
        </div>
    </div>
    <script src="{{ asset('admin/assets/js/site.min.js') }}"></script>
</body>

</html>

resources/views/admin/setting.blade.php
@extends('layouts.admin')
@section('content')


<div class="page-hero page-container" id="page-hero">
    <div class="padding d-flex">
        <div class="page-title">
            <h2 class="text-md text-highlight">Setting</h2><small class="text-muted">Configure the things</small></div>
    </div>
</div>
<div class="page-content page-container" id="page-content">
    <div class="padding">
        <div id="accordion">
            <p class="text-muted"><strong>Account</strong></p>
            <div class="card">
                <div class="d-flex align-items-center px-4 py-3 pointer" data-toggle="collapse" data-parent="#accordion" data-target="#c_1">
                    <div><span class="w-48 avatar circle bg-info-lt" data-toggle-class="loading"><img src="{{ asset('admin/assets/img/a1.jpg') }}" alt="."></span></div>
                    <div class="mx-3 d-none d-md-block"><strong>
                    @if(Auth::guard('admin'))
                    {{ ucwords(Auth::guard('admin')->user()->name) }}
                    @else
                        Anonym
                    @endif
                    </strong>
                        <!-- <div class="text-sm text-muted">jacqueline@company.co</div> -->
                    </div>
                    <div class="flex"></div>
                    <div class="mx-3"><i data-feather="chevron-right"></i></div>
                    <div><a href="signin.1.html" class="text-prmary text-sm">Sign Out</a></div>
                </div>
                <div class="collapse p-4" id="c_1">
                    <form role="form">
                        <div class="form-group">
                            <label>Profile picture</label>
                            <div class="custom-file">
                                <input type="file" class="custom-file-input" id="customFile">
                                <label class="custom-file-label" for="customFile">Choose file</label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label>First Name</label>
                            <input type="text" class="form-control">
                        </div>
                        <div class="form-group">
                            <label>Last Name</label>
                            <input type="text" class="form-control">
                        </div>
                        <button type="submit" class="btn btn-primary mt-2">Update</button>
                    </form>
                </div>
                <div class="d-flex align-items-center px-4 py-3 b-t"><i data-feather="refresh-cw"></i>
                    <div class="px-3">
                        <div>Sync</div>
                        <div class="text-sm text-muted">On - Sync everything</div>
                    </div>
                    <div class="flex"></div><span><label class="ui-switch ui-switch-md"><input type="checkbox" checked="checked"> <i></i></label></span></div>
                <div class="d-flex align-items-center px-4 py-3 b-t pointer" data-toggle="collapse" data-parent="#accordion" data-target="#c_2"><i data-feather="lock"></i>
                    <div class="px-3">
                        <div>Password</div>
                    </div>
                    <div class="flex"></div>
                    <div><i data-feather="chevron-right"></i></div>
                </div>
                <div class="collapse p-4" id="c_2">
                    <form role="form">
                        <div class="form-group">
                            <label>Old Password</label>
                            <input type="password" class="form-control">
                        </div>
                        <div class="form-group">
                            <label>New Password</label>
                            <input type="password" class="form-control">
                        </div>
                        <div class="form-group">
                            <label>New Password Again</label>
                            <input type="password" class="form-control">
                        </div>
                        <button type="submit" class="btn btn-primary mt-2">Update</button>
                    </form>
                </div>
                <div class="d-flex align-items-center px-4 py-3 b-t pointer" data-toggle="collapse" data-parent="#accordion" data-target="#c_3"><i data-feather="credit-card"></i>
                    <div class="px-3">
                        <div>Payment methods</div>
                    </div>
                    <div class="flex"></div>
                    <div><i data-feather="chevron-right"></i></div>
                </div>
                <div class="collapse p-4" id="c_3">
                    <form role="form">
                        <div class="form-group">
                            <label>Paypal account</label>
                            <input type="input" class="form-control">
                        </div>
                        <button type="submit" class="btn btn-primary mt-2">Update</button>
                    </form>
                </div>
                <div class="d-flex align-items-center px-4 py-3 b-t pointer" data-toggle="collapse" data-parent="#accordion" data-target="#c_4"><i data-feather="map-pin"></i>
                    <div class="px-3">
                        <div>Addresses and more</div>
                    </div>
                    <div class="flex"></div>
                    <div><i data-feather="chevron-right"></i></div>
                </div>
                <div class="collapse p-4" id="c_4">
                    <form role="form">
                        <div class="form-group">
                            <label>URL</label>
                            <input type="text" class="form-control">
                        </div>
                        <div class="form-group">
                            <label>Company</label>
                            <input type="text" class="form-control">
                        </div>
                        <div class="form-group">
                            <label>Location</label>
                            <input type="text" class="form-control">
                        </div>
                        <button type="submit" class="btn btn-primary mt-2">Update</button>
                    </form>
                </div>
            </div>
            <p class="text-muted"><strong>Notifications</strong></p>
            <div class="card">
                <div class="d-flex align-items-center px-4 py-3">
                    <div>Anyone seeing my profile page</div>
                    <div class="flex"></div><span><label class="ui-switch ui-switch-md"><input type="checkbox"> <i></i></label></span></div>
                <div class="d-flex align-items-center px-4 py-3 b-t">
                    <div>Anyone follow me</div>
                    <div class="flex"></div><span><label class="ui-switch ui-switch-md"><input type="checkbox" checked="checked"> <i></i></label></span></div>
                <div class="d-flex align-items-center px-4 py-3 b-t">
                    <div>Anyone send me a message</div>
                    <div class="flex"></div><span><label class="ui-switch ui-switch-md"><input type="checkbox" checked="checked"> <i></i></label></span></div>
                <div class="d-flex align-items-center px-4 py-3 b-t">
                    <div>Anyone invite me to group</div>
                    <div class="flex"></div><span><label class="ui-switch ui-switch-md"><input type="checkbox"> <i></i></label></span></div>
                <div class="d-flex align-items-center px-4 py-3 b-t">
                    <div>Update</div>
                    <div class="flex"></div><span><label class="ui-switch ui-switch-md"><input type="checkbox" checked="checked"> <i></i></label></span></div>
            </div>
            <p class="text-muted"><strong>Emails</strong></p>
            <div class="card">
                <div class="d-flex align-items-center px-4 py-3">
                    <div>Anyone posts a comment on my post</div>
                    <div class="flex"></div><span><label class="ui-switch ui-switch-md"><input type="checkbox"> <i></i></label></span></div>
                <div class="d-flex align-items-center px-4 py-3 b-t">
                    <div>Anyone follow me</div>
                    <div class="flex"></div><span><label class="ui-switch ui-switch-md"><input type="checkbox" checked="checked"> <i></i></label></span></div>
                <div class="d-flex align-items-center px-4 py-3 b-t">
                    <div>Anyone repost</div>
                    <div class="flex"></div><span><label class="ui-switch ui-switch-md"><input type="checkbox"> <i></i></label></span></div>
            </div>
            <p class="text-muted"><strong>Security</strong></p>
            <div class="card">
                <div class="d-flex align-items-center px-4 py-3 b-t pointer" data-toggle="collapse" data-parent="#accordion" data-target="#c_5">
                    <div>Delete account?</div>
                    <div class="flex"></div>
                    <div><i data-feather="chevron-right"></i></div>
                </div>
                <div class="collapse p-4" id="c_5">
                    <div class="py-3">
                        <p>Are you sure to delete your account?</p>
                        <button type="button" class="btn btn-white">No</button>
                        <button type="button" class="btn btn-danger">Yes</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection