routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/ 
Route::get('/', 'HomeController@index')->name('index');
Route::get('/produk', 'ProductController@index')->name('product');
Route::get('/pages/{slug}', 'PagesController@show')->name('detail.pages');
Route::get('/produk-detail/{slug}', 'ProductController@show')->name('detail.product');
// Route::get('/tentang-kami', 'HomeController@about')->name('about');
// Route::get('/program-reseller', 'HomeController@reseller')->name('reseller');
Route::get('/testimonial', 'HomeController@testimonial')->name('testimonial');
Route::get('/kontak-kami', 'HomeController@contact')->name('contact');
Route::post('/message/save', 'MessageController@store')->name('message.store');
Route::get('/category/{categoryName}', 'ProductController@index')->name('category');

Route::post('/search', 'ProductSearchController@index')->name('search.product');

Route::get('/blog/all', 'BlogController@index')->name('all.blog');
Route::get('/blog/{blogSlug}', 'BlogController@show')->name('detail.blog');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login')->name('client.login.submit');

Route::prefix('ajax')->name('ajax.')->group(function(){
    Route::get('premium', 'AjaxController@getPremiumProduct')->name('premium');
    Route::get('sale', 'AjaxController@getSaleProduct')->name('sale');
    Route::get('new', 'AjaxController@getNewProduct')->name('new');
    Route::get('available', 'AjaxController@getAvailProduct')->name('available');
    Route::get('soon', 'AjaxController@getSoonProduct')->name('soon');

    Route::get('color/{color?}', 'AjaxController@getColorProduct')->name('color');
});

        //preview blog
    Route::get('/preview/{blogSlug}', 'BlogController@preview')->name('preview.blog')->middleware('admin');
    Route::get('/page-preview/{pagesSlug}', 'PagesController@preview')->name('pagepreview.blog')->middleware('admin');

Route::prefix('admin')->name('admin.')->namespace('Admin')->group(function(){
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('/login', 'Auth\LoginController@login')->name('login.submit');
    Route::post('logout', 'Auth\LoginController@logout')->name('logout');
    Route::get('register','Auth\LoginController@showRegisterPage');
    Route::post('register', 'Auth\LoginController@register')->name('register.submit');

    Route::group(['middleware' => ['admin']], function () {

        Route::get('kontak-kami', 'ContactUsController@index')->name('contact_us');
        Route::post('kontak-kami/save', 'ContactUsController@save')->name('contact_us.save');

        // profile
        Route::get('profile','HomeController@showProfile');


        // dashboard
        Route::get('dashboard', 'HomeController@dashboard')->name('dashboard');


        // product
        Route::get('products', 'ProductController@index')->name('products');
        Route::get('product/add', 'ProductController@create')->name('add.product');
        Route::post('product/save', 'ProductController@store')->name('create.product');
        Route::get('product/edit/{id}', 'ProductController@edit')->name('edit.product');
        Route::post('product/update', 'ProductController@update')->name('update.product');
        Route::get('product/remove/{id}', 'ProductController@destroy')->name('remove.product');
        Route::post('product/removeall', 'ProductController@destroyAll')->name('removeall.product');

        // contact master
        Route::get('contact_master', 'ContactController@index')->name('contact');
        Route::get('contact_master/add', 'ContactController@create')->name('add.contact');
        Route::post('contact_master/save', 'ContactController@store')->name('create.contact');
        Route::get('contact_master/edit/{id}', 'ContactController@edit')->name('edit.contact');
        Route::post('contact_master/update', 'ContactController@update')->name('update.contact');
        Route::get('contact_master/remove/{id}', 'ContactController@destroy')->name('remove.contact');
        Route::post('contact_master/removeall', 'ContactController@destroyAll')->name('removeall.contact');

        //category product
        Route::get('product/category', 'ProductCategoryController@index')->name('category.product');
        Route::get('category/add', 'ProductCategoryController@create')->name('create.category');
        Route::get('category/edit/{id}', 'ProductCategoryController@edit')->name('edit.category');
        Route::post('category/save', 'ProductCategoryController@store')->name('store.category');
        Route::post('category/update', 'ProductCategoryController@update')->name('update.category');
        Route::get('category/remove/{id}', 'ProductCategoryController@destroy')->name('remove.category');
        Route::post('category/removeall', 'ProductCategoryController@destroyAll')->name('removeall.category');


        //blogs
        Route::get('blogs', 'BlogController@index')->name('blogs');
        Route::get('blog/add', 'BlogController@create')->name('create.blog');
        Route::post('blog/save', 'BlogController@store')->name('store.blog');
        Route::get('blog/edit/{id}', 'BlogController@edit')->name('edit.blog');
        Route::post('blog/update', 'BlogController@update')->name('update.blog');
        Route::get('blog/remove/{id}', 'BlogController@destroy')->name('remove.blog');
        Route::post('blog/removeall', 'BlogController@destroyAll')->name('removeall.blog');


        //category blog
        Route::get('blog/category', 'BlogCategoryController@index')->name('category.blog');
        Route::get('blog/category/add', 'BlogCategoryController@create')->name('add.category.blog');
        Route::post('blog/category/save', 'BlogCategoryController@store')->name('create.category.blog');
        Route::get('blog/category/edit/{id}', 'BlogCategoryController@edit')->name('remove.category.blog');
        Route::post('blog/category/update', 'BlogCategoryController@update')->name('update.category.blog');
        Route::get('blog/category/remove/{id}', 'BlogCategoryController@destroy')->name('remove.category.blog');
        Route::post('blog/category/removeall', 'BlogCategoryController@destroyAll')->name('removeall.category.blog');


        //tags blog
        Route::get('blog/tag', 'BlogTagController@index')->name('tag.blog');
        Route::get('blog/tag/add', 'BlogTagController@create')->name('add.tag.blog');
        Route::post('blog/tag/save', 'BlogTagController@store')->name('create.tag.blog');
        Route::get('blog/tag/edit/{id}', 'BlogTagController@edit')->name('edit.tag.blog');
        Route::post('blog/tag/update', 'BlogTagController@update')->name('update.tag.blog');
        Route::get('blog/tag/remove/{id}', 'BlogTagController@destroy')->name('remove.tag.blog');
        Route::post('blog/tag/removeall', 'BlogTagController@destroyAll')->name('removeall.tag.blog');


        //menu setting
        Route::get('menu', 'MenuController@index')->name('menu');
        Route::get('menu/add', 'MenuController@create')->name('add.menu');
        Route::post('menu/save', 'MenuController@store')->name('create.menu');
        Route::get('menu/edit/{id}', 'MenuController@edit')->name('edit.menu');
        Route::post('menu/update', 'MenuController@update')->name('update.menu');
        Route::get('menu/remove/{id}', 'MenuController@destroy')->name('remove.menu');
        Route::post('menu/removeall', 'MenuController@destroyAll')->name('removeall.menu');

        //pages
        Route::get('pages', 'PagesController@index')->name('pages');
        Route::get('pages/add', 'PagesController@create')->name('add.pages');
        Route::post('pages/save', 'PagesController@store')->name('create.pages');
        Route::get('pages/edit/{id}', 'PagesController@edit')->name('edit.pages');
        Route::post('pages/update', 'PagesController@update')->name('update.pages');
        Route::get('pages/remove/{id}', 'PagesController@destroy')->name('remove.pages');
        Route::post('pages/removeall', 'PagesController@destroyAll')->name('removeall.pages');

        //testimonial
        Route::get('testimonial', 'TestimonialController@index')->name('show.testimonial');
        Route::get('testimonial/add', 'TestimonialController@create')->name('add.testimonial');
        Route::post('testimonial/save', 'TestimonialController@store')->name('create.testimonial');
        Route::get('testimonial/edit/{id}', 'TestimonialController@edit')->name('update.TestimonialController');
        Route::post('testimonial/update', 'TestimonialController@update')->name('update.TestimonialController');    
        Route::get('testimonial/remove/{id}', 'TestimonialController@destroy')->name('remove.TestimonialController');
        Route::post('testimonial/removeall', 'TestimonialController@destroyAll')->name('removeall.TestimonialControllerg');

        //general
        Route::get('general', 'GeneralController@index')->name('logo');
        Route::post('general/save_logo_header', 'GeneralController@save_logo_header')->name('save_header.logo');
        Route::post('general/save_logo_footer', 'GeneralController@save_logo_footer')->name('save_footer.logo');
        Route::post('general/save_banner', 'GeneralController@save_banner')->name('SaveBanner');
        Route::post('general/save_prod_banner', 'GeneralController@save_prod_banner')->name('SaveProdBanner');

        // users
        Route::get('admins', 'AdminsController@index')->name('admins');

resources/views/admin/admins/create_admin.blade.php
@extends('layouts.admin')
@section('content')

<div class="page-hero page-container" id="page-hero">
    <div class="padding d-flex">
        <div class="page-title">
            <h2 class="text-md text-highlight">Tambah Pengguna CMS</h2><small class="text-muted">tambahkan pengguna</small></div>
    </div>
</div>
<div class="page-content page-container" id="page-content">
    <div class="padding">
        @if ($errors->any())
            <div class="row alert alert-danger">
                <div class="col-sm-10">
                    <ul style="margin: auto;">
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                <div class="col-sm-2">                
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            </div>
        @endif
        <form action="{{ route('admin.save') }}" method="POST" enctype="multipart/form-data">
        @csrf
        <div class="row">
            <div class="col-sm-8">
                    <div class="card">
                        <div class="card-header"><strong>Pengguna Baru</strong></div>
                        <div class="card-body">
                            <div class="form-row">
                                <div class="form-group col-sm-12">
                                    <label>Nama</label>
                                    <input type="text" name="nama" class="form-control" placeholder="Nama Pengguna" required>
                                </div>
                                <div class="form-group col-sm-12">
                                    <label>No Telp</label>
                                    <input type="text" name="phone_number" class="form-control" placeholder="Nomor Telp">
                                </div>
                                <div class="form-group col-sm-12">
                                    <label>Email</label>
                                    <input type="text" name="email" class="form-control" placeholder="Email Pengguna" required>
                                </div>
                                <div class="form-group col-sm-12">
                                    <label>Password</label>
                                    <input type="password" name="password" class="form-control" placeholder="Password" required>
                                </div>
                                <div class="form-group col-sm-12">
                                    <label>Ulangi Password</label>
                                    <input type="password" name="password_confirmation" class="form-control" placeholder="Ulangi Password">
                                </div>

                            </div>
                            <div class="text-right pt-2">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </div>
                    </div>
            </div>
        </div>
        </form>
    </div>
</div>
@endsection

resources/views/admin/admins/edit_admin.blade.php
@extends('layouts.admin')
@section('content')

<div class="page-hero page-container" id="page-hero">
    <div class="padding d-flex">
        <div class="page-title">
            <h2 class="text-md text-highlight">Tambah Pengguna CMS</h2><small class="text-muted">tambahkan pengguna</small></div>
    </div>
</div>
<div class="page-content page-container" id="page-content">
    <div class="padding">
        @if ($errors->any())
            <div class="row alert alert-danger">
                <div class="col-sm-10">
                    <ul style="margin: auto;">
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                <div class="col-sm-2">                
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            </div>
        @endif
        <form action="{{ route('admin.update') }}" method="POST" enctype="multipart/form-data">
        <input type="hidden" name="admin_id" value="{{ $admin->id }}">
        @csrf
        <div class="row">
            <div class="col-sm-8">
                    <div class="card">
                        <div class="card-header"><strong>Pengguna Baru</strong></div>
                        <div class="card-body">
                            <div class="form-row">
                                <div class="form-group col-sm-12">
                                    <label>Nama</label>
                                    <input type="text" name="nama" class="form-control" value="{{ $admin->name }}" required>
                                </div>
                                <div class="form-group col-sm-12">
                                    <label>No Telp</label>
                                    <input type="text" name="phone_number" class="form-control" value="{{ $admin->no_telp }}">
                                </div>
                                <div class="form-group col-sm-12">
                                    <label>Email</label>
                                    <input type="text" name="email" class="form-control" value="{{ $admin->email }}" required>
                                </div>

                            </div>
                            
                            <div class="text-left pt-2">
                            <a href="{{ route('admin.admins') }}" class="btn btn-light"><i data-feather="arrow-left"></i><span class="d-none d-sm-inline mx-1">Kembali</span></a>
                            <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                            <div class="text-right pt-2">
                                
                            </div>
                        </div>
                    </div>
            </div>
        </div>
        </form>
    </div>
</div>
@endsection

resources/views/admin/admins/list_admin.blade.php
@extends('layouts.admin')
@section('content')


<div id="messages"></div>
<div class="page-hero page-container" id="page-hero" data-plugin="admins">
    <div class="padding d-flex">
        <div class="page-title">
            <h2 class="text-md text-highlight">Admins</h2><small class="text-muted">List Admin</small></div>
            <div class="flex"></div>
            <div><a href="{{ route('admin.create') }}" class="btn btn-md btn-primary"><span class="d-none d-sm-inline mx-1">Tambah Admin</span> <i data-feather="arrow-right"></i></a></div>
    </div>
</div>
<div class="page-content page-container" id="page-content">
    <div class="padding">
        <div class="mb-5">
            <div class="toolbar">
                
            </div>
            <div class="table-responsive">
                <table class="table table-theme table-row v-middle">
                    <thead>
                        <tr>
                            <th style="width:20px">
                                <label class="ui-check m-0">
                                    <input type="checkbox" id="select-all" ><i></i></label>
                            </th>
                            <th class="text-muted" data-toggle-class="asc">Nama</th>
                            <th class="text-muted"><span class="d-none d-sm-block">Email</span></th>
                            <th class="text-muted"><span class="d-none d-sm-block">Status</span></th>
                            <th style="width:50px"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($admins as $item)
                        <tr class="v-middle" data-id="{{ $item->id }}">
                            <td>
                                <label class="ui-check m-0">
                                <input type="checkbox" name="id[]" value="{{ $item->id }}"> <i></i></label>
                            </td>
                            <td class="flex"><a href="{{ url('admin/detail/'.$item->id) }}" class="item-title text-color">{!! substr($item->name, 0, 50) !!}</a>
                            </td>
                            <td><span class="item-amount d-none d-sm-block text-sm [object Object]">{{ $item->email }}</span></td>
                            <td><span class="item-amount d-none d-sm-block text-sm [object Object]">{{ ucfirst($item->status) }}</span></td>
                            <td>
                                <div class="item-action dropdown">
                                    <a href="#" data-toggle="dropdown" class="text-muted">
                                        <i data-feather="more-vertical"></i>
                                    </a>
                                    <div class="dropdown-menu dropdown-menu-right bg-black" role="menu">
                                        <a class="dropdown-item edit" href="{{ route('admin.edit', $item->id) }}">Edit</a>
                                        <a class="dropdown-item trash" href="{{ route('admin.remove', $item->id) }}" onclick="return confirm('Anda yakin ingin menghapus pengguna ini?');" >Delete</a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            <div class="d-flex">
            {!! $admins->render() !!}
            <small class="text-muted py-2 mx-2">Total <span id="count">{{ number_format($admins->total(), 0) }}</span> items</small></div>
        </div>
    </div>
</div>
@endsection